# Site Settings
title: My Resume
url: 'granittemaj.github.io'
baseurl: '/online-cv' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Granit Temaj
tagline: 
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'An IT engineer, web developer, hiking guide, runner, and blogger, with a passion for technology, traveling, running, and outdoors.<br>When I was 21, I backpacked 26 countries in Europe. Not metaphorically - I literally did it. Besides this, I climbed around 60 mountains and finished 2 half marathons until now. <br> While I was hiking, I thought about quitting approximately 500 times. (And that’s a lowball estimate). But despite the high winds, high altitude, mental and physical weakness, and trail mix overdose, I kept going. I’m that person. When I say I'll accomplish something, it will happen.
<br>
Now, I put that perseverance to work as an Operational Consultant at Kosbit LLC. I don’t have to climb any mountains…but I do have to move them.<br>I’m well-versed in web development, planning, project coordinating, operations, working under pressure and problem - solving skills.<br>'

#sidebar links
email: granit.temaj@gmail.com
phone: +386 49 665 104
website: alpventurer.com #do not add http://
linkedin: granittemaj
github: granittemaj
twitter: '@granit_t'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
